# Generated by Django 2.0.1 on 2018-03-02 04:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('jaipur', django.db.models.manager.Manager()),
            ],
        ),
    ]
